#!/usr/bin/env python3
"""Capture deterministic tensors from a validated scaffolded MLX package.

The package contains user-owned Python code and is executed with the current
user's authority. Package validation detects drift from scaffold_port.py; it is
not a sandbox. ``--allow-modified`` acknowledges that drift explicitly.
"""
from __future__ import annotations

import argparse
import importlib
import json
import os
import platform
import re
import stat
import sys
from pathlib import Path
from typing import Any

from _capture_common import (
    DEFAULT_GENERATE_STEPS,
    DEFAULT_MAX_OUTPUT_MB,
    MAX_MANIFEST_JSON_BYTES,
    MAX_TOKEN_IDS,
    SCHEMA_VERSION,
    absolute_lexical,
    build_model_record,
    read_bounded_json,
    tensor_inventory,
    validate_capture_limits,
    validate_capture_manifest,
    validate_input_mode,
    validate_output_path,
    write_capture_outputs,
)
from _common import SkillError, sha256_file


SCAFFOLD_MANIFEST = "scaffold-manifest.json"
SUPPORTED_GENERATOR_VERSION = "1.0.2"
MAX_SCAFFOLD_MANIFEST_BYTES = 16 * 1024 * 1024
MAX_CONFIG_BYTES = 16 * 1024 * 1024
MAX_TOKENIZER_CONFIG_BYTES = 16 * 1024 * 1024
HEADER_RE = re.compile(
    r"# Generated by scaffold_port\.py ([0-9]+\.[0-9]+\.[0-9]+) "
    r"from inspection sha256:([0-9a-f]{64})\.\Z"
)
SHA256_RE = re.compile(r"[0-9a-f]{64}\Z")
EXECUTION_FILES = ("capture.py", "config.json", "config.py", "model.py")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Capture source-compatible tensors from a scaffolded MLX package",
        epilog=(
            "Trust model: the scaffold is user-owned Python code that this command executes. "
            "Validation surfaces drift; --allow-modified acknowledges drift but does not sandbox code."
        ),
    )
    parser.add_argument("--package", help="Directory produced by scaffold_port.py")
    parser.add_argument(
        "--mode",
        choices=("dense-decoder", "encoder"),
        default="dense-decoder",
        help="Capture contract (default: dense-decoder)",
    )
    parser.add_argument("--weights", help="Directory produced by convert_checkpoint.py")
    parser.add_argument("--output", help="Destination .npz archive")
    parser.add_argument("--manifest", help="Default: <output stem>.manifest.json")
    parser.add_argument("--prompt", action="append", help="Prompt to tokenize locally; repeatable")
    parser.add_argument(
        "--prompts-file",
        action="append",
        help="Bounded UTF-8 file containing one prompt per non-empty line; repeatable",
    )
    parser.add_argument(
        "--token-ids",
        nargs="+",
        help="One tokenizer-free token sequence as space- or comma-separated integers",
    )
    parser.add_argument(
        "--attention-mask",
        nargs="+",
        help="Encoder mode only: one 0/1 value per tokenizer-free token ID",
    )
    parser.add_argument(
        "--tokenizer",
        help="Local built-in Transformers tokenizer directory required for prompt mode",
    )
    parser.add_argument("--generate-steps", type=int, default=DEFAULT_GENERATE_STEPS)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--keep-dtype", action="store_true")
    parser.add_argument("--max-output-mb", type=float, default=DEFAULT_MAX_OUTPUT_MB)
    parser.add_argument(
        "--allow-modified",
        action="store_true",
        help="Execute a drifted user-owned scaffold after surfacing modified files",
    )
    parser.add_argument(
        "--fault-inject-target",
        help="Validation-only: add a deterministic error to one floating target capture",
    )
    parser.add_argument(
        "--validate-manifest",
        help="Validate one source-compatible capture manifest without importing MLX",
    )
    return parser.parse_args(argv)


def _strict_fields(value: Any, fields: set[str], *, label: str) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != fields:
        raise SkillError(f"{label} has an invalid field set")
    return value


def _regular_directory(value: str, *, label: str) -> Path:
    path = absolute_lexical(Path(value))
    if path.is_symlink() or not path.is_dir():
        raise SkillError(f"{label} must be a local, non-symlink directory: {value}")
    return path


def _regular_package_file(package: Path, name: str) -> Path:
    path = package / name
    if path.is_symlink():
        raise SkillError(f"scaffold package file must not be a symlink: {name}")
    try:
        metadata = path.stat()
    except OSError as exc:
        raise SkillError(f"scaffold package is missing required file {name}: {exc}") from exc
    if not stat.S_ISREG(metadata.st_mode):
        raise SkillError(f"scaffold package file must be regular: {name}")
    return path


def _header_identity(path: Path) -> tuple[str, str] | None:
    try:
        with path.open("r", encoding="utf-8") as handle:
            first_line = handle.readline(512).rstrip("\r\n")
    except (OSError, UnicodeDecodeError) as exc:
        raise SkillError(f"could not read generated header from {path.name}: {exc}") from exc
    match = HEADER_RE.fullmatch(first_line)
    return (match.group(1), match.group(2)) if match else None


def _validate_scaffold_manifest(payload: Any) -> dict[str, Any]:
    manifest = _strict_fields(
        payload,
        {
            "schema_version",
            "generator",
            "inspection_sha256",
            "config_sha256",
            "files",
            "tensors",
        },
        label="scaffold manifest",
    )
    if manifest["schema_version"] != 1:
        raise SkillError("scaffold manifest schema_version must be integer 1")
    generator = _strict_fields(
        manifest["generator"],
        {"name", "version"},
        label="scaffold manifest generator",
    )
    if generator != {"name": "scaffold_port.py", "version": SUPPORTED_GENERATOR_VERSION}:
        raise SkillError(
            f"scaffold manifest must come from scaffold_port.py {SUPPORTED_GENERATOR_VERSION}"
        )
    for field in ("inspection_sha256", "config_sha256"):
        if not isinstance(manifest[field], str) or SHA256_RE.fullmatch(manifest[field]) is None:
            raise SkillError(f"scaffold manifest {field} must be a lowercase SHA-256 digest")
    files = manifest["files"]
    if not isinstance(files, list):
        raise SkillError("scaffold manifest files must be a list")
    names: list[str] = []
    for index, item in enumerate(files):
        record = _strict_fields(
            item,
            {"path", "size_bytes", "sha256"},
            label=f"scaffold manifest files[{index}]",
        )
        if record["path"] not in EXECUTION_FILES:
            raise SkillError("scaffold manifest contains an unexpected execution file")
        if type(record["size_bytes"]) is not int or record["size_bytes"] < 0:
            raise SkillError("scaffold manifest file size must be a non-negative integer")
        if not isinstance(record["sha256"], str) or SHA256_RE.fullmatch(record["sha256"]) is None:
            raise SkillError("scaffold manifest file digest must be lowercase SHA-256")
        names.append(record["path"])
    if names != sorted(EXECUTION_FILES):
        raise SkillError("scaffold manifest must attest the complete execution file set")
    tensors = manifest["tensors"]
    if not isinstance(tensors, list) or not tensors:
        raise SkillError("scaffold manifest tensors must be a non-empty list")
    tensor_names: list[str] = []
    for index, item in enumerate(tensors):
        record = _strict_fields(
            item,
            {"key", "shape"},
            label=f"scaffold manifest tensors[{index}]",
        )
        if not isinstance(record["key"], str) or not record["key"]:
            raise SkillError("scaffold manifest tensor key must be non-empty")
        if not isinstance(record["shape"], list) or not all(
            type(dimension) is int and dimension >= 0 for dimension in record["shape"]
        ):
            raise SkillError("scaffold manifest tensor shape is invalid")
        tensor_names.append(record["key"])
    if tensor_names != sorted(tensor_names) or len(tensor_names) != len(set(tensor_names)):
        raise SkillError("scaffold manifest tensor keys must be sorted and unique")
    return manifest


def validate_package(package: Path, *, allow_modified: bool) -> dict[str, Any]:
    paths = {name: _regular_package_file(package, name) for name in EXECUTION_FILES}
    manifest_path = package / SCAFFOLD_MANIFEST
    modified: list[str] = []
    manifest: dict[str, Any] | None = None
    manifest_error: SkillError | None = None
    try:
        manifest = _validate_scaffold_manifest(
            read_bounded_json(
                manifest_path,
                MAX_SCAFFOLD_MANIFEST_BYTES,
                label="scaffold manifest",
            )
        )
    except SkillError as exc:
        manifest_error = exc
        modified.append(SCAFFOLD_MANIFEST)

    header_identities = {
        name: _header_identity(paths[name]) for name in ("capture.py", "config.py", "model.py")
    }
    if manifest is not None:
        expected_header = (
            manifest["generator"]["version"],
            manifest["inspection_sha256"],
        )
        records = {record["path"]: record for record in manifest["files"]}
        for name in EXECUTION_FILES:
            metadata = paths[name].stat()
            if (
                metadata.st_size != records[name]["size_bytes"]
                or sha256_file(paths[name]) != records[name]["sha256"]
            ):
                modified.append(name)
        if sha256_file(paths["config.json"]) != manifest["config_sha256"]:
            modified.append("config.json")
        for name, identity in header_identities.items():
            if identity != expected_header:
                modified.append(name)
    else:
        identities = {identity for identity in header_identities.values() if identity is not None}
        if len(identities) != 1 or any(identity is None for identity in header_identities.values()):
            modified.extend(name for name, identity in header_identities.items() if identity is None)
        elif next(iter(identities))[0] != SUPPORTED_GENERATOR_VERSION:
            modified.extend(header_identities)

    modified = sorted(set(modified))
    if modified and not allow_modified:
        detail = f": {manifest_error}" if manifest_error is not None else ""
        raise SkillError(
            "scaffold package has unvalidated modifications"
            f"{detail}; changed files: {', '.join(modified)}; "
            "review the user-owned code and pass --allow-modified to execute it"
        )
    return {
        "manifest": manifest,
        "modified": bool(modified),
        "modified_files": modified,
    }


def validate_weights(weights: Path, scaffold: dict[str, Any] | None) -> Path:
    weights_path = weights / "model.safetensors"
    target_path = weights / "target-manifest.json"
    report_path = weights / "conversion-report.json"
    for path in (weights_path, target_path, report_path):
        if path.is_symlink() or not path.is_file():
            raise SkillError(
                "--weights must be a complete output directory from convert_checkpoint.py; "
                f"missing regular {path.name}"
            )
    target = read_bounded_json(target_path, MAX_MANIFEST_JSON_BYTES, label="target manifest")
    target = _strict_fields(
        target,
        {"schema_version", "format", "file", "tensors"},
        label="target manifest",
    )
    if target["schema_version"] != 1 or target["format"] != "safetensors" or target["file"] != "model.safetensors":
        raise SkillError("target manifest is not a convert_checkpoint.py safetensors manifest")
    if not isinstance(target["tensors"], list) or not target["tensors"]:
        raise SkillError("target manifest tensors must be a non-empty list")
    target_shapes: dict[str, list[int]] = {}
    for index, item in enumerate(target["tensors"]):
        record = _strict_fields(
            item,
            {"key", "shape", "dtype"},
            label=f"target manifest tensors[{index}]",
        )
        if (
            not isinstance(record["key"], str)
            or not record["key"]
            or record["key"] in target_shapes
            or not isinstance(record["shape"], list)
            or not all(type(value) is int and value >= 0 for value in record["shape"])
            or not isinstance(record["dtype"], str)
            or not record["dtype"]
        ):
            raise SkillError("target manifest tensor entry is invalid")
        target_shapes[record["key"]] = record["shape"]
    if scaffold is not None:
        expected = {item["key"]: item["shape"] for item in scaffold["tensors"]}
        if target_shapes != expected:
            raise SkillError("converted target manifest does not match the scaffold parameter contract")
    report = _strict_fields(
        read_bounded_json(report_path, MAX_MANIFEST_JSON_BYTES, label="conversion report"),
        {
            "schema_version", "counts", "transforms_applied", "dtype_policy",
            "memory_budget", "inputs", "outputs",
        },
        label="conversion report",
    )
    if report["schema_version"] != 1:
        raise SkillError("conversion report schema_version must be integer 1")
    counts = _strict_fields(
        report["counts"],
        {
            "ignored_source_tensors", "mapped_source_tensors", "mapping_entries",
            "source_tensors", "target_tensors",
        },
        label="conversion report counts",
    )
    if not all(type(value) is int and value >= 0 for value in counts.values()):
        raise SkillError("conversion report counts must be non-negative integers")
    if counts["target_tensors"] != len(target_shapes):
        raise SkillError("conversion report target tensor count is inconsistent")
    transforms = report["transforms_applied"]
    if not isinstance(transforms, dict) or not all(
        isinstance(key, str) and key and type(value) is int and value >= 0
        for key, value in transforms.items()
    ):
        raise SkillError("conversion report transforms_applied is invalid")
    dtype_policy = _strict_fields(
        report["dtype_policy"], {"global", "targets"}, label="conversion report dtype_policy"
    )
    if not isinstance(dtype_policy["global"], str) or not isinstance(dtype_policy["targets"], dict):
        raise SkillError("conversion report dtype_policy is invalid")
    memory_budget = _strict_fields(
        report["memory_budget"],
        {
            "limit_bytes", "aggregate_materialized_bytes", "estimated_peak_bytes",
            "source_materialized_bytes", "target_materialized_bytes", "target_encoded_bytes",
        },
        label="conversion report memory_budget",
    )
    if not all(type(value) is int and value >= 0 for value in memory_budget.values()):
        raise SkillError("conversion report memory_budget must contain non-negative integers")
    inputs = _strict_fields(
        report["inputs"], {"mapping", "source_files"}, label="conversion report inputs"
    )
    _validate_conversion_file_record(inputs["mapping"], label="conversion report mapping")
    if not isinstance(inputs["source_files"], list) or not inputs["source_files"]:
        raise SkillError("conversion report source_files must be a non-empty list")
    for index, record in enumerate(inputs["source_files"]):
        _validate_conversion_file_record(record, label=f"conversion report source_files[{index}]")
    outputs = _strict_fields(
        report["outputs"], {"weights", "target_manifest"}, label="conversion report outputs"
    )
    _validate_conversion_file_record(
        outputs["weights"], label="conversion report weights", writer=True
    )
    _validate_conversion_file_record(
        outputs["target_manifest"], label="conversion report target_manifest"
    )
    _enforce_conversion_digest(outputs["weights"], weights_path, label="converted weights")
    _enforce_conversion_digest(
        outputs["target_manifest"], target_path, label="converted target manifest"
    )
    return weights_path


def _validate_conversion_file_record(
    value: Any,
    *,
    label: str,
    writer: bool = False,
) -> None:
    fields = {"name", "size_bytes", "sha256"} | ({"writer"} if writer else set())
    record = _strict_fields(value, fields, label=label)
    if not isinstance(record["name"], str) or not record["name"] or "/" in record["name"]:
        raise SkillError(f"{label} name must be a basename")
    if type(record["size_bytes"]) is not int or record["size_bytes"] < 0:
        raise SkillError(f"{label} size_bytes must be a non-negative integer")
    if not isinstance(record["sha256"], str) or SHA256_RE.fullmatch(record["sha256"]) is None:
        raise SkillError(f"{label} sha256 must be a lowercase SHA-256 digest")
    if writer and (not isinstance(record["writer"], str) or not record["writer"]):
        raise SkillError(f"{label} writer must be non-empty")


def _enforce_conversion_digest(record: dict[str, Any], path: Path, *, label: str) -> None:
    metadata = path.stat()
    if (
        record["name"] != path.name
        or record["size_bytes"] != metadata.st_size
        or record["sha256"] != sha256_file(path)
    ):
        raise SkillError(f"{label} does not match conversion-report.json attestation")


def _load_config(package: Path) -> dict[str, Any]:
    config = read_bounded_json(package / "config.json", MAX_CONFIG_BYTES, label="config.json")
    if not isinstance(config, dict):
        raise SkillError("config.json must contain an object")
    return config


def _build_numpy_inputs(
    prompts: list[str],
    token_ids: list[int] | None,
    tokenizer_value: str | None,
    config: dict[str, Any],
    np: Any,
    explicit_attention_mask: list[int] | None = None,
    encoder_mode: bool = False,
) -> tuple[Any, Any]:
    if token_ids is not None:
        vocab_size = config.get("vocab_size")
        if type(vocab_size) is int and any(value >= vocab_size for value in token_ids):
            raise SkillError(f"--token-ids values must be below config vocab_size={vocab_size}")
        values = np.asarray([token_ids], dtype=np.int32)
        if explicit_attention_mask is None:
            return values, np.ones_like(values, dtype=np.int32)
        return values, np.asarray([explicit_attention_mask], dtype=np.int32)
    if tokenizer_value is None:
        raise SkillError("prompt mode requires --tokenizer pointing at the local source model")
    tokenizer_dir = _regular_directory(tokenizer_value, label="tokenizer")
    tokenizer_config = tokenizer_dir / "tokenizer_config.json"
    if tokenizer_config.exists():
        value = read_bounded_json(
            tokenizer_config,
            MAX_TOKENIZER_CONFIG_BYTES,
            label="tokenizer_config.json",
        )
        if isinstance(value, dict) and value.get("auto_map"):
            raise SkillError("tokenizer_config.json declares remote code; capture_mlx.py refuses it")
    os.environ["HF_HUB_OFFLINE"] = "1"
    os.environ["TRANSFORMERS_OFFLINE"] = "1"
    try:
        from transformers import AutoTokenizer
    except ImportError as exc:
        raise SkillError(
            "prompt mode requires optional package 'transformers'; "
            "install it with python3 -m pip install transformers"
        ) from exc
    try:
        tokenizer = AutoTokenizer.from_pretrained(
            str(tokenizer_dir),
            local_files_only=True,
            trust_remote_code=False,
        )
    except Exception as exc:
        raise SkillError(f"could not load a built-in local tokenizer: {exc}") from exc
    if len(prompts) > 1:
        if tokenizer.pad_token_id is None:
            raise SkillError("tokenizer has no pad token; use one prompt or --token-ids")
        tokenizer.padding_side = "right" if encoder_mode else "left"
    encoded = tokenizer(
        prompts,
        return_tensors="np",
        padding=len(prompts) > 1,
        add_special_tokens=True,
    )
    input_ids = np.asarray(encoded["input_ids"], dtype=np.int32)
    if input_ids.ndim != 2 or input_ids.shape[1] > MAX_TOKEN_IDS:
        raise SkillError("local tokenizer did not produce bounded rank-2 input_ids")
    attention_mask = np.asarray(
        encoded.get("attention_mask", np.ones_like(input_ids)),
        dtype=np.int32,
    )
    return input_ids, attention_mask


def _import_generated_model(package: Path) -> Any:
    sys.path.insert(0, str(package))
    for name in ("config", "model"):
        sys.modules.pop(name, None)
    try:
        module = importlib.import_module("model")
    except Exception as exc:
        raise SkillError(f"could not import validated scaffold model.py: {exc}") from exc
    module_path = Path(getattr(module, "__file__", "")).resolve()
    if module_path != (package / "model.py").resolve():
        raise SkillError("imported model module did not come from the validated scaffold")
    return module


def _zero_padded_query_rows(value: Any, attention_mask: Any, mx: Any) -> Any:
    if value.ndim < 2 or value.shape[:2] != attention_mask.shape:
        return value
    query_mask = attention_mask.astype(mx.bool_)
    for _ in range(value.ndim - 2):
        query_mask = query_mask[..., None]
    return mx.where(query_mask, value, mx.zeros_like(value))


def _capture(
    package: Path,
    weights_path: Path,
    input_ids_np: Any,
    attention_mask_np: Any,
    generate_steps: int,
    keep_dtype: bool,
    np: Any,
    mx: Any,
    mode: str = "dense-decoder",
    fault_inject_target: str | None = None,
) -> dict[str, Any]:
    generated_model = _import_generated_model(package)
    try:
        model = generated_model.load_model(package / "config.json", weights_path)
        input_ids = mx.array(input_ids_np, dtype=mx.int32)
        attention_mask = mx.array(attention_mask_np, dtype=mx.int32)
        if mode == "encoder":
            if generate_steps != 0:
                raise SkillError("--mode encoder requires --generate-steps 0")
            _, _, captures = model(
                input_ids,
                attention_mask=attention_mask,
                capture=True,
            )
            tensors = {
                "input_ids": input_ids,
                "attention_mask": attention_mask,
                **{
                    name: _zero_padded_query_rows(value, attention_mask, mx)
                    for name, value in captures.items()
                },
            }
            _inject_capture_fault(tensors, fault_inject_target, mx)
            getattr(mx, "eval")(*tensors.values())
            arrays: dict[str, Any] = {}
            for name, value in sorted(tensors.items()):
                array = np.asarray(value)
                if np.issubdtype(array.dtype, np.floating) and not keep_dtype:
                    array = array.astype(np.float32, copy=False)
                if array.dtype.hasobject:
                    raise SkillError(f"tensor {name} produced an unsafe object dtype")
                arrays[name] = np.ascontiguousarray(array)
            return arrays

        logits, _, captures = model(input_ids, attention_mask=attention_mask, capture=True)
        sequence = input_ids
        mask = attention_mask
        generated = []
        for _ in range(generate_steps):
            step_logits, _ = model(sequence, attention_mask=mask)
            next_token = mx.argmax(step_logits[:, -1, :], axis=-1).astype(mx.int32)
            generated.append(next_token)
            sequence = mx.concatenate((sequence, next_token[:, None]), axis=1)
            mask = mx.concatenate((mask, mx.ones((mask.shape[0], 1), dtype=mx.int32)), axis=1)
        generated_ids = (
            mx.stack(generated, axis=1)
            if generated
            else mx.zeros((input_ids.shape[0], 0), dtype=mx.int32)
        )
        tensors = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            **{
                name: _zero_padded_query_rows(value, attention_mask, mx)
                for name, value in captures.items()
            },
            "logits": _zero_padded_query_rows(logits, attention_mask, mx),
            "generated_token_ids": generated_ids,
        }
        _inject_capture_fault(tensors, fault_inject_target, mx)
        getattr(mx, "eval")(*tensors.values())
        arrays: dict[str, Any] = {}
        for name, value in sorted(tensors.items()):
            array = np.asarray(value)
            if np.issubdtype(array.dtype, np.floating) and not keep_dtype:
                array = array.astype(np.float32, copy=False)
            if array.dtype.hasobject:
                raise SkillError(f"tensor {name} produced an unsafe object dtype")
            arrays[name] = np.ascontiguousarray(array)
        return arrays
    finally:
        if sys.path and sys.path[0] == str(package):
            sys.path.pop(0)
        for name in ("config", "model"):
            sys.modules.pop(name, None)


def _inject_capture_fault(tensors: dict[str, Any], target: str | None, mx: Any) -> None:
    if target is None:
        return
    if target not in tensors:
        raise SkillError(f"--fault-inject-target is not a captured tensor: {target}")
    value = tensors[target]
    if target in {"input_ids", "attention_mask", "generated_token_ids"}:
        raise SkillError("--fault-inject-target requires a floating capture")
    tensors[target] = value + mx.array(0.5, dtype=value.dtype)


def _run_manifest_validation(path_value: str) -> int:
    payload = read_bounded_json(
        Path(path_value),
        MAX_MANIFEST_JSON_BYTES,
        label="oracle manifest",
    )
    manifest = validate_capture_manifest(payload)
    print(json.dumps({"ok": True, "schema_version": manifest["schema_version"]}, sort_keys=True))
    return 0


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        if args.validate_manifest:
            conflicting = any((
                args.package is not None,
                args.weights is not None,
                args.output is not None,
                args.manifest is not None,
                bool(args.prompt),
                bool(args.prompts_file),
                bool(args.token_ids),
                args.tokenizer is not None,
                args.keep_dtype,
                args.allow_modified,
                args.fault_inject_target is not None,
                args.generate_steps != DEFAULT_GENERATE_STEPS,
                args.seed != 0,
                args.max_output_mb != DEFAULT_MAX_OUTPUT_MB,
                args.mode != "dense-decoder",
                bool(args.attention_mask),
            ))
            if conflicting:
                raise SkillError("--validate-manifest cannot be combined with capture arguments")
            return _run_manifest_validation(args.validate_manifest)

        cap_bytes = validate_capture_limits(args.generate_steps, args.max_output_mb)
        if args.package is None or args.weights is None or args.output is None:
            raise SkillError("--package, --weights, and --output are required for MLX capture")
        prompts, token_ids = validate_input_mode(args.token_ids, args.prompt, args.prompts_file)
        if args.attention_mask and args.mode != "encoder":
            raise SkillError("--attention-mask is supported only with --mode encoder")
        if args.attention_mask and token_ids is None:
            raise SkillError("--attention-mask requires --token-ids")
        if token_ids is not None and args.tokenizer is not None:
            raise SkillError("--tokenizer is only valid with --prompt or --prompts-file")
        package = _regular_directory(args.package, label="package")
        weights = _regular_directory(args.weights, label="weights")
        package_state = validate_package(package, allow_modified=args.allow_modified)
        weights_path = validate_weights(weights, package_state["manifest"])
        config = _load_config(package)

        output = validate_output_path(Path(args.output), label="NPZ output")
        if output.suffix.lower() != ".npz":
            raise SkillError("--output must end with .npz")
        manifest = validate_output_path(
            Path(args.manifest) if args.manifest else output.with_suffix(".manifest.json"),
            label="manifest output",
        )
        if output == manifest:
            raise SkillError("NPZ and manifest outputs must be different paths")
        protected = {absolute_lexical(package / name) for name in EXECUTION_FILES}
        protected.add(absolute_lexical(package / SCAFFOLD_MANIFEST))
        protected.add(absolute_lexical(weights_path))
        if output in protected or manifest in protected:
            raise SkillError("capture outputs must not overwrite package code, config, or weights")

        try:
            import mlx
            import mlx.core as mx
        except ImportError as exc:
            raise SkillError(
                "capture_mlx.py requires optional package 'mlx'; "
                "install it with python3 -m pip install mlx"
            ) from exc
        try:
            import numpy as np
        except ImportError as exc:
            raise SkillError(
                "capture_mlx.py requires optional package 'numpy'; "
                "install it with python3 -m pip install numpy"
            ) from exc

        np.random.seed(args.seed % (2**32))
        explicit_attention_mask = None
        if args.attention_mask is not None:
            pieces = [
                piece.strip()
                for value in args.attention_mask
                for piece in value.split(",")
            ]
            try:
                explicit_attention_mask = [int(piece, 10) for piece in pieces]
            except ValueError as exc:
                raise SkillError("--attention-mask must contain only 0/1 integers") from exc
            if (
                token_ids is None
                or len(explicit_attention_mask) != len(token_ids)
                or any(value not in (0, 1) for value in explicit_attention_mask)
            ):
                raise SkillError("--attention-mask must contain one 0/1 value per token ID")
        input_ids_np, attention_mask_np = _build_numpy_inputs(
            prompts,
            token_ids,
            args.tokenizer,
            config,
            np,
            explicit_attention_mask,
            args.mode == "encoder",
        )
        arrays = _capture(
            package,
            weights_path,
            input_ids_np,
            attention_mask_np,
            args.generate_steps,
            args.keep_dtype,
            np,
            mx,
            args.mode,
            args.fault_inject_target,
        )
        manifest_payload = {
            "schema_version": SCHEMA_VERSION,
            "model": build_model_record(package, package / "config.json", [weights_path]),
            "capture": {
                "mode": args.mode,
                "input_mode": "token_ids" if token_ids is not None else "prompt",
                "prompts": prompts if token_ids is None else None,
                "token_ids": token_ids,
                "attention_mask": attention_mask_np.astype(np.int64).tolist(),
                "generate_steps": args.generate_steps,
                "seed": args.seed,
                "dtype_policy": "keep" if args.keep_dtype else "float32",
            },
            "tensors": tensor_inventory(arrays),
            "libraries": {
                "python": platform.python_version(),
                "numpy": str(np.__version__),
                "torch": "not-used",
                "transformers": "not-used",
            },
        }
        write_capture_outputs(
            output,
            manifest,
            arrays,
            manifest_payload,
            cap_bytes,
            np,
        )
        print(json.dumps({
            "manifest": str(manifest),
            "npz": str(output),
            "ok": True,
            "package_modified": package_state["modified"],
            "modified_files": package_state["modified_files"],
            "tensor_count": len(arrays),
            "mlx": str(getattr(mlx, "__version__", "unknown")),
        }, sort_keys=True, allow_nan=False))
        return 0
    except (SkillError, ImportError, OSError, RuntimeError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
